mailserver:
  username: "username"
  password: "password"
  from: "email@email.com"
  subject: "Ověřovací kód SSPŠ Minecraft"
  message: "Váš ověřovací kód je <b>%CODE%</b>.<br>Kód vyprší za 5 minut. Pokud jste tento kód nežádali, můžete ho ignorovat."
  host: "smtp"
  port: 578
authentication:
  time: 300