name: EmailVerifier
main: me.sarahlacerda.main.Main
author: Sarah Lacerda
version: 1.0
api-version: 1.17
description: An email verification plugin
commands:
  register:
    description: Command to request an authentication code for your MC account via an e-mail
    usage: /<command>
    aliases: [ auth ]
  code:
    description: Command to verify your MC account with the code received via your e-mail
    usage: /<command>
  password:
    description: Command to request an authentication code for your MC account via an e-mail
    usage: /<command>
    aliases: [ auth ]
    code:
      description: Command to verify your MC account with the code received via your e-mail
      usage: /<command>
  resetpassword:
    description: Command to request an authentication code for your MC account via an e-mail
    usage: /<command>
    aliases: [ auth ]
    code:
      description: Command to verify your MC account with the code received via your e-mail
      usage: /<command>
  login:
    description: Command to request an authentication code for your MC account via an e-mail
    usage: /<command>
    aliases: [ auth ]
    code:
      description: Command to verify your MC account with the code received via your e-mail
      usage: /<command>